config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [] do
    resource :directives do
      get :qr_code, on: :collection
    end
  end
end

app/models/directive.rb
class Directive < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :content
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :directive, dependent: :destroy

  def has_directive?
    directive.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/directives_controller.rb
class DirectivesController < ApplicationController
  helper_method :directive
  before_action :authenticate_user!, except: [:show, :qr_code]
  include ApplicationHelper

  def show
  end

  def new
  end

  def edit
  end

  def create
    user.create_directive!(directive_params)
    flash[:success] = t(".success")
    redirect_to root_path
  rescue ActiveRecord::RecordInvalid
    flash[:alert] = t(".failure")
    render "new"
  end

  def update
    directive.update! directive_params
    flash[:success] = t(".success")
    redirect_to root_path
  rescue ActiveRecord::RecordInvalid
    flash[:alert] = t(".failure")
    render "edit"
  end

  def destroy
    directive.destroy!
    flash[:success] = t(".success")
    redirect_to root_path
  end

  def qr_code
    svg_file = Tempfile.new(["qr_code", ".svg"])
    svg_file.write qr_helper(user)
    send_file svg_file, type: "image/svg+xml",
                        x_sendfile: true
  end

  private

  def directive_params
    params.require(:directive).permit(:content)
  end

  def user
    @user ||= User.find params[:user_id]
  end

  def directive
    @directive ||= user.directive || user.build_directive
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def qr_helper(user = current_user)
    url = user_directives_url(user)
    qrcode = RQRCode::QRCode.new(url)


    qrcode.as_svg(offset: 0, color: '000', 
                    shape_rendering: 'crispEdges', 
                    module_size: 9).html_safe
  end

  MARKDOWN_RENDERER = Redcarpet::Markdown.
                      new(Redcarpet::Render::HTML,
                          autolink: true, tables: true)

  def markdown(text)
    MARKDOWN_RENDERER.render(text).html_safe
  end

  def home_page_markdown
    File.read("#{Rails.root}/README.md")
  end
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success", "secondary").
      tap do |hash|
      hash["primary"] = hash.delete "notice"
      hash["warning"] = hash.delete "error"
    end.compact
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_css_overrides.html.erb
<% if Rails.env.test? %>
  <style type="text/css">
    * {
      transition-property: none !important;
    }
  </style>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| -%>
    <div class="<%= key.to_s %> callout" aria-label="Alert" data-closable>
      <p><%= value %></p>
      <button class="close-button" 
              aria-label="Dismiss alert" 
              type="button" data-close>
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end -%>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/application/_top_bar.html.erb
<div class="title-bar" data-responsive-toggle="main-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle></button>
  <div class="title-bar-title">Menu</div>
</div>

<div class="top-bar" id="main-menu">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <%= link_to root_path do %>
        <li class="menu-text">Death Store </li>
      <% end %>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu" data-responsive-menu="drilldown medium-dropdown">
      <% if user_signed_in? %>
        <li><%= link_to(t(".edit_user"), edit_user_registration_path) %></li>

        <li><%= link_to(t(".sign_out"), destroy_user_session_path, method: :delete) %></li>
      <% else %>
        <li><%= link_to t(".sign_in") , new_user_session_path %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/directives/_form.html.erb
<% content_error = directive.errors[:content].present? %>
<%= f.label :content, 
  class: (content_error ? "is-invalid-label" : nil) do %>
  <%= t(".content") %>
  <%= f.text_area :content, required: false, placeholder: t(".content_placeholder") %>

  <% directive.errors.full_messages_for(:content).each do |mesage| %>

    <%= content_tag :small, mesage , class: "form-error is-visible" %>
  <% end %>
<% end %>

app/views/directives/edit.html.erb
<div class="row">
  <div class="medium-8  medium-centered columns">
    <%= form_for(directive, url: user_directives_path(current_user), html: { method: :put }) do |f| %>
      <h2 class="text-centered"><%= t(".title") %></h2>
      <%= render 'form', f: f %>
      <%= f.submit t(".submit"), class: "button expanded" %>
    <% end %>
  </div>
</div>

app/views/directives/new.html.erb
<div class="row">
  <div class="medium-8  medium-centered columns">
    <%= form_for(directive, url: user_directives_path(current_user), html: { method: :post }) do |f| %>
      <h2 class="text-centered"><%= t(".title") %></h2>
      <%= render 'form', f: f %>
      <%= f.submit t(".submit"), class: "button expanded" %>
    <% end %>
  </div>
</div>

app/views/directives/show.html.erb
<p class="callout">
  <%= directive.content %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <%#
    Configure default and controller-, and view-specific titles in
    config/locales/en.yml. For more see:
    https://github.com/calebthompson/title#usage
  %>
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
  <%= render "javascript" %>
</head>
<body class="<%= body_class %>">
  <%= render "top_bar" -%>
  <%= render "flashes" -%>
  <%= yield %>
  <%= render "css_overrides" %>
</body>
</html>

app/views/pages/home.html.erb
<div class="callout primary">
  <div class="row column text-center">
    <% if user_signed_in? %>
      <h1>Signed in!</h1>
    <% else %>
      <%= link_to t(".sign_up"), new_user_registration_path, class: "large button" %> 
    <% end %>
  </div>
</div>

<div class="row">
  <div class="medium-8 medium-centered columns">
    <% if user_signed_in? %>
      <% if current_user.has_directive? %>
        <article>
          <p class="callout"><%= current_user.directive.content %></p>
          <%= link_to t(".download_directive"), qr_code_user_directives_path(current_user), class: "button expanded large" %>
          <%= link_to t(".edit_directive"), edit_user_directives_path(current_user), class: "button expanded large" %>
          <%= link_to t(".delete_directive"), user_directives_path(current_user), class: "button expanded large", method: :delete %>

          <%=  qr_helper %>

        </article>
      <% else %>
        <%= link_to t(".create_directive"), new_user_directives_path(current_user), class: "button expanded large" %>
      <% end %>

    <% else %>    
      <!-- <p>Place holder for mission statement</p> -->
      <%= markdown home_page_markdown %>
    <% end %>
  </div>
</div>

app/views/refills/_flashes.html.erb
<div class="flash-success">
  <span>This is a success message <a href="#">with a link</a></span>
</div>

<div class="flash-error">
  <span>This is an error message <a href="#">with a link</a></span>
</div>

<div class="flash-notice">
  <span>This is an notice message <a href="#">with a link</a></span>
</div>

<div class="flash-alert">
  <span>This is an alert message <a href="#">with a link</a></span>
</div>